apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3               # Number of pod replicas
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: nginx            # Docker image for the container
          ports:
            - containerPort: 80            # Container's port
      containers:
        - name: my-app-01
          image: nginx            # Docker image for the container
          ports:
            - containerPort: 80            # Container's port
         