apiVersion: batch/v1
kind: Job
metadata: 
  name: my-job
  labels:
    type: batch-job
spec:
  template:
    spec:
      containers:
        - name: my-job
          image: busybox:latest
          command: ["/bin/sh" , "-c", "echo ' i love kubernetes'"]
      restartPolicy: Never      # OnFailure