apiVersion: v1
kind: Pod
metadata: 
  name: polinux-pod
  namespace: demo
spec:
  containers:
  - name: polinux-mem-req
    image: polinux/stress
    resources:
      requests:
        memory: "10Mi"
        cpu: "20"
      limits:
        memory: "200Mi"
        cpu: "100"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]