apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: my-app
    type: front-end
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
      - containerPort: 80
     