apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: my-app
    type: front-end
spec:
  replicas: 3
  selector:
    matchLables:
      app: my-app
template:
  metadata:
    name: nginx-replicaset
  spec:
    containers:
    - name: nginx-replicaset
      image: nginx
      ports: 
        - containerPort: 80

      