apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "sleep 500"]
    volumeMounts:               
    - mountPath: "/mnt/storage"   
      name: my-storage
  volumes:                       
  - name: my-storage
    persistentVolumeClaim:        
      claimName: demo-pvc
