apiVersion: v1
metadata:
  name: my-pod
  labels:
    name: my-app
spec:
  containers:
    - name: nginx-pod
      image: nginx
      ports:
        containerPort: 80

---
  

apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
  labels:
    app: my-app
spec:
  type: ClusterIP      # Default type, internally accessible only
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80         # Port to expose the service on
      targetPort: 80   # Port that the application container listens on
  
