apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: my-app
    type: front-end
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-pod
  labels:
    app: my-nodeport-svc
spec:
  type: NodePort
  selector:
    app: my-app
    type: front-end
  ports:
  - protocol: TCP
    port: 80 # The port your service will listen to inside the cluster
    targetPort: 80 # The port your application is listening to on the pod
    nodePort: 30007 # The port exposed on the node (optional, auto-assigned if omitted)
